import type { Pattern } from "@/lib/types";

// Local typed data keeps the MVP backend-free and makes a future MDX migration explicit.
export const patterns: Pattern[] = [
  {
    slug: "fake-scarcity",
    title: "Fake Scarcity",
    category: "Urgency & Scarcity",
    summary: "Only 3 rooms left. Allegedly. Conveniently. Forever.",
    description:
      "Fake scarcity claims that a product, seat, room, or offer is almost gone without making the constraint verifiable or meaningful.",
    severity: 5,
    psychology: ["Loss Aversion", "FOMO", "Cognitive Load"],
    examples: ["Only 3 left at this price.", "14 people are viewing this item right now."],
    ethicalAlternative:
      "Show real inventory, explain why it is limited, and remove pressure copy when the number is not actionable.",
    origin: "Travel booking, ecommerce, ticketing, and flash-sale interfaces.",
  },
  {
    slug: "countdown-reset",
    title: "Countdown Reset",
    category: "Urgency & Scarcity",
    summary: "The timer reaches zero, takes a small bow, and starts again.",
    description:
      "A deadline is presented as decisive, but the same offer remains available after the countdown ends or reappears on refresh.",
    severity: 5,
    psychology: ["Loss Aversion", "FOMO", "Cognitive Load"],
    examples: ["Offer expires in 04:59.", "Refresh the page and the same exclusive deadline returns."],
    ethicalAlternative: "Use real deadlines, disclose timezone and terms, and let expired promotions actually expire.",
    origin: "Limited-time deal pages, webinar funnels, and checkout overlays.",
  },
  {
    slug: "confirmshaming",
    title: "Confirmshaming",
    category: "Social Engineering",
    summary: "No thanks, I hate saving money.",
    description:
      "A refusal action is written to insult, guilt, or belittle the user for making a legitimate choice.",
    severity: 3,
    psychology: ["Social Proof", "Commitment Bias"],
    examples: ["No, I prefer paying full price.", "I do not care about my health."],
    ethicalAlternative: "Label decline actions neutrally and respect the user's decision without editorial commentary.",
    origin: "Newsletter modals, ecommerce coupons, and lead-capture popups.",
  },
  {
    slug: "roach-motel",
    title: "Roach Motel",
    category: "Subscription Traps",
    summary: "Easy to enter. Curiously ceremonial to leave.",
    description:
      "A product makes signup, purchase, or subscription simple while cancellation requires hidden paths, calls, delays, or repeated persuasion.",
    severity: 5,
    psychology: ["Commitment Bias", "Cognitive Load", "Loss Aversion"],
    examples: ["Subscribe in one click, cancel through a phone queue.", "The cancellation link is buried behind retention screens."],
    ethicalAlternative: "Make cancellation as easy as signup and confirm outcomes immediately in plain language.",
    origin: "Subscription software, gyms, media services, and membership programs.",
  },
  {
    slug: "decoy-pricing",
    title: "Decoy Pricing",
    category: "Pricing Manipulation",
    summary: "One plan exists mostly to make another plan look reasonable.",
    description:
      "A deliberately unattractive option anchors the user's comparison so the intended plan feels like the sensible middle.",
    severity: 3,
    psychology: ["Anchoring", "Cognitive Load"],
    examples: ["Basic for 5, Pro for 19, Ultra for 199.", "A print-only plan nudges users toward a bundle."],
    ethicalAlternative: "Design plans around distinct user needs and make tradeoffs clear without artificial anchors.",
    origin: "SaaS plan tables, media subscriptions, and product bundles.",
  },
  {
    slug: "hidden-cancellation",
    title: "Hidden Cancellation",
    category: "Subscription Traps",
    summary: "Cancellation exists, in the same sense that a secret door exists.",
    description:
      "The user can cancel, but the path is obscured through vague labels, nested settings, or support-only workflows.",
    severity: 4,
    psychology: ["Cognitive Load", "Commitment Bias"],
    examples: ["Manage plan hides the cancel action three screens deep.", "The help article names a button that does not exist."],
    ethicalAlternative: "Put cancellation in account settings with direct labels, clear consequences, and immediate confirmation.",
    origin: "Consumer subscriptions, trials, and account dashboards.",
  },
  {
    slug: "forced-continuity",
    title: "Forced Continuity",
    category: "Subscription Traps",
    summary: "The free trial ends quietly; the invoice speaks clearly.",
    description:
      "A trial converts into a paid subscription without timely reminders, clear billing expectations, or simple opt-out.",
    severity: 4,
    psychology: ["Default Bias", "Commitment Bias"],
    examples: ["Start free, billed annually after seven days.", "Reminder emails are absent or written like promotional mail."],
    ethicalAlternative: "Send clear reminders, disclose billing dates upfront, and offer no-card trials when practical.",
    origin: "Streaming, software trials, education platforms, and consumer apps.",
  },
  {
    slug: "privacy-zuckering",
    title: "Privacy Zuckering",
    category: "Privacy Manipulation",
    summary: "Sharing more than intended, with excellent onboarding confetti.",
    description:
      "The interface nudges users into disclosing personal information or granting permissions they did not clearly understand.",
    severity: 5,
    psychology: ["Default Bias", "Cognitive Load", "Social Proof"],
    examples: ["Find friends requires broad contact access.", "Profile visibility defaults to public after setup."],
    ethicalAlternative: "Ask for data at the moment of need, explain the benefit, and default to the most private reasonable option.",
    origin: "Social products, mobile onboarding, and data-heavy consumer apps.",
  },
  {
    slug: "social-proof-inflation",
    title: "Social Proof Inflation",
    category: "Trust & Authority Abuse",
    summary: "Everyone is buying this. Everyone, apparently, has a busy afternoon.",
    description:
      "Popularity claims are exaggerated, outdated, vague, or simulated to imply confidence that the evidence does not support.",
    severity: 4,
    psychology: ["Social Proof", "FOMO"],
    examples: ["4,812 people bought this today.", "Trending in your area, with no source or timeframe."],
    ethicalAlternative: "Use specific, recent, auditable signals and avoid popularity claims when the data is weak.",
    origin: "Marketplaces, travel sites, crowdfunding, and ecommerce.",
  },
  {
    slug: "visual-hierarchy-manipulation",
    title: "Visual Hierarchy Manipulation",
    category: "Interface Manipulation",
    summary: "The preferred button is a cathedral; the alternative is a footnote.",
    description:
      "Color, scale, contrast, and placement make one choice feel like the natural action while making alternatives hard to notice.",
    severity: 3,
    psychology: ["Default Bias", "Cognitive Load"],
    examples: ["Accept all is bright and large; reject is a low-contrast text link.", "The paid option is visually framed as progress."],
    ethicalAlternative: "Give materially different choices comparable visibility and plain labels.",
    origin: "Consent dialogs, upgrade screens, checkout flows, and onboarding.",
  },
  {
    slug: "cookie-labyrinth",
    title: "Cookie Labyrinth",
    category: "Privacy Manipulation",
    summary: "Accept is one button. Refuse is a regional governance exercise.",
    description:
      "Cookie controls make consent withdrawal or granular privacy choices much harder than accepting tracking.",
    severity: 5,
    psychology: ["Cognitive Load", "Default Bias"],
    examples: ["Accept all is immediate; manage opens seventeen toggles.", "Reject all is hidden below scroll or behind categories."],
    ethicalAlternative: "Offer equal-weight accept and reject controls, with optional granular settings for users who want them.",
    origin: "Cookie banners, consent management platforms, and ad-funded sites.",
  },
  {
    slug: "infinite-scroll",
    title: "Infinite Scroll",
    category: "Attention Capture",
    summary: "A bottomless page, now with plausible deniability.",
    description:
      "Content loads continuously so stopping requires more self-control than continuing.",
    severity: 3,
    psychology: ["Commitment Bias", "Cognitive Load"],
    examples: ["Feeds append new posts as the user approaches the end.", "Stopping points are removed from browsing sessions."],
    ethicalAlternative: "Add natural stopping cues, session controls, and ways to resume intentionally.",
    origin: "Social feeds, video platforms, shopping grids, and news apps.",
  },
  {
    slug: "notification-addiction",
    title: "Notification Addiction",
    category: "Mobile Addiction",
    summary: "A red dot, the smallest possible emergency.",
    description:
      "Badges, alerts, and push prompts are tuned to create habitual checking rather than meaningful interruption.",
    severity: 4,
    psychology: ["FOMO", "Commitment Bias"],
    examples: ["A badge appears for low-value updates.", "Push prompts frame refusal as missing out."],
    ethicalAlternative: "Bundle low-priority updates, let users set notification intent, and avoid urgency styling for routine events.",
    origin: "Mobile apps, messaging products, marketplaces, and games.",
  },
  {
    slug: "default-bias",
    title: "Default Bias",
    category: "Interface Manipulation",
    summary: "The default is not neutral. It is a decision wearing a cardigan.",
    description:
      "Users are nudged toward a selected option because changing defaults requires attention, effort, or confidence.",
    severity: 3,
    psychology: ["Default Bias", "Cognitive Load"],
    examples: ["Marketing emails are opted in by default.", "Annual billing is preselected in a pricing toggle."],
    ethicalAlternative: "Use defaults that protect users, disclose implications, and require active choice for sensitive decisions.",
    origin: "Forms, checkout pages, onboarding, privacy settings, and plan selectors.",
  },
  {
    slug: "preselected-options",
    title: "Preselected Options",
    category: "Pricing Manipulation",
    summary: "The box was checked before you arrived. Hospitality, perhaps.",
    description:
      "Optional add-ons, permissions, upgrades, or commitments are selected before the user makes an active choice.",
    severity: 4,
    psychology: ["Default Bias", "Anchoring"],
    examples: ["Insurance is added to the basket automatically.", "A donation or tip is preselected during checkout."],
    ethicalAlternative: "Make optional costs and permissions opt-in, especially when they affect billing or privacy.",
    origin: "Ticketing, travel, checkout, donation flows, and mobile setup.",
  },
  {
    slug: "drip-pricing",
    title: "Drip Pricing",
    category: "Pricing Manipulation",
    summary: "The price starts polite and becomes honest only at the end.",
    description:
      "A product is advertised with a low headline price while mandatory fees, service charges, taxes, or handling costs appear gradually through checkout.",
    severity: 5,
    psychology: ["Anchoring", "Commitment Bias", "Cognitive Load"],
    examples: ["A 39€ ticket becomes 61€ after platform, processing, and delivery fees.", "A hotel rate excludes unavoidable resort fees until checkout."],
    ethicalAlternative: "Show the total unavoidable price upfront and explain optional costs before the user commits time.",
    origin: "Ticketing, travel, delivery, event platforms, and marketplaces.",
  },
  {
    slug: "sneak-into-basket",
    title: "Sneak Into Basket",
    category: "Pricing Manipulation",
    summary: "A small extra arrives in the basket with admirable confidence.",
    description:
      "An extra product, service, warranty, donation, or protection plan is added to the cart without a clear active choice from the user.",
    severity: 5,
    psychology: ["Default Bias", "Cognitive Load"],
    examples: ["A warranty is silently added below the main item.", "A donation line appears in the basket unless removed manually."],
    ethicalAlternative: "Require explicit opt-in for every paid extra and make removal obvious.",
    origin: "Ecommerce, travel checkout, electronics retail, and donation flows.",
  },
  {
    slug: "bait-and-switch",
    title: "Bait and Switch",
    category: "Trust & Authority Abuse",
    summary: "The button promised one thing. The next screen has other ambitions.",
    description:
      "The user is led to expect one outcome, then the interface delivers a different action, offer, price, or commitment.",
    severity: 5,
    psychology: ["Commitment Bias", "Cognitive Load"],
    examples: ["A download button opens an installer upsell.", "A free template leads to a required subscription step."],
    ethicalAlternative: "Make the outcome of each action explicit and keep promises across every step of the flow.",
    origin: "Download sites, lead funnels, trial products, and affiliate pages.",
  },
  {
    slug: "disguised-ads",
    title: "Disguised Ads",
    category: "Trust & Authority Abuse",
    summary: "An ad wearing the local costume of content.",
    description:
      "Paid placements are styled to look like editorial content, organic search results, or native recommendations while disclosure is muted.",
    severity: 4,
    psychology: ["Social Proof", "Cognitive Load"],
    examples: ["Sponsored results use the same layout as organic results.", "A recommendation card hides its ad label in low contrast."],
    ethicalAlternative: "Label paid placements prominently and visually distinguish ads from editorial or organic content.",
    origin: "Search pages, news sites, marketplaces, app stores, and social feeds.",
  },
  {
    slug: "nagging",
    title: "Nagging",
    category: "Attention Capture",
    summary: "The same request returns until refusal starts to feel like labor.",
    description:
      "A product repeatedly interrupts the user with prompts, upsells, permissions, ratings, or reminders after they have already declined.",
    severity: 3,
    psychology: ["Commitment Bias", "Cognitive Load"],
    examples: ["Rate us appears after every launch.", "Enable notifications returns after repeated dismissals."],
    ethicalAlternative: "Respect declines, add cooldowns, and let users reopen prompts from settings when they are ready.",
    origin: "Mobile apps, SaaS onboarding, games, and ecommerce apps.",
  },
  {
    slug: "trick-questions",
    title: "Trick Questions",
    category: "Interface Manipulation",
    summary: "A checkbox grammar exam with billing consequences.",
    description:
      "Questions are worded with negatives, double negatives, or confusing conditions so users accidentally consent or opt in.",
    severity: 4,
    psychology: ["Cognitive Load", "Default Bias"],
    examples: ["Untick this box if you do not want to miss offers.", "I do not wish to avoid receiving updates."],
    ethicalAlternative: "Use positive, direct wording and separate each meaningful choice into a clear control.",
    origin: "Signup forms, marketing consent, checkout flows, and account settings.",
  },
  {
    slug: "misdirection",
    title: "Misdirection",
    category: "Interface Manipulation",
    summary: "Attention is escorted away from the part that costs money.",
    description:
      "The interface uses layout, emphasis, animation, imagery, or copy to draw attention away from important terms, costs, or consequences.",
    severity: 4,
    psychology: ["Cognitive Load", "Anchoring"],
    examples: ["A bright discount dominates the page while recurring billing is tiny.", "A free shipping message distracts from a handling fee."],
    ethicalAlternative: "Give material information comparable prominence to promotional claims.",
    origin: "Checkout, pricing pages, subscription signup, and promotional landing pages.",
  },
  {
    slug: "comparison-prevention",
    title: "Comparison Prevention",
    category: "Pricing Manipulation",
    summary: "Three plans, six units, and no way to compare like with like.",
    description:
      "Prices, quantities, bundles, billing periods, or feature names are presented inconsistently to make rational comparison difficult.",
    severity: 3,
    psychology: ["Cognitive Load", "Anchoring"],
    examples: ["One plan is monthly, another annual, another per seat.", "Bundles mix storage, credits, tokens, and add-ons without unit prices."],
    ethicalAlternative: "Show normalized prices and comparable units beside each option.",
    origin: "SaaS pricing, telecom plans, subscriptions, groceries, and cloud services.",
  },
  {
    slug: "fake-discount",
    title: "Fake Discount",
    category: "Pricing Manipulation",
    summary: "A sale price with a very creative memory of the original.",
    description:
      "A discount is calculated from an inflated, rarely used, or recently increased reference price to create a misleading sense of value.",
    severity: 4,
    psychology: ["Anchoring", "Loss Aversion"],
    examples: ["Was 129€, now 59€, despite selling at 59€ most of the year.", "A countdown sale repeats with the same discount every week."],
    ethicalAlternative: "Use honest reference prices and disclose the period during which the original price was used.",
    origin: "Ecommerce, retail promotions, travel deals, and online courses.",
  },
  {
    slug: "fake-activity",
    title: "Fake Activity",
    category: "Social Engineering",
    summary: "Someone in Bristol just bought this exact anxiety.",
    description:
      "The interface displays recent purchases, signups, views, or locations that are simulated, exaggerated, or not relevant to the current item.",
    severity: 4,
    psychology: ["Social Proof", "FOMO"],
    examples: ["Maria from Lisbon just booked this room.", "27 people are checking out this product now."],
    ethicalAlternative: "Show real, recent, relevant activity only when it helps users make an informed decision.",
    origin: "Booking widgets, ecommerce popups, course platforms, and fundraising pages.",
  },
  {
    slug: "friend-spam",
    title: "Friend Spam",
    category: "Social Engineering",
    summary: "Your address book becomes a growth strategy.",
    description:
      "A product asks for contact access and then nudges, invites, or messages other people in ways the user did not clearly intend.",
    severity: 5,
    psychology: ["Social Proof", "Commitment Bias", "Cognitive Load"],
    examples: ["Import contacts sends invitations by default.", "A referral flow preselects every contact."],
    ethicalAlternative: "Ask before every invitation, preview recipients and messages, and never send social messages by default.",
    origin: "Social networks, referral programs, productivity apps, and mobile onboarding.",
  },
  {
    slug: "permission-priming",
    title: "Permission Priming",
    category: "Privacy Manipulation",
    summary: "The app asks nicely before the operating system asks seriously.",
    description:
      "A custom prompt emotionally frames a permission request before the real system dialog appears, often making refusal feel harmful or antisocial.",
    severity: 3,
    psychology: ["Commitment Bias", "Social Proof"],
    examples: ["Enable location to make the community safer.", "Allow notifications so you never disappoint your team."],
    ethicalAlternative: "Request permissions only at the moment of need and explain functional consequences without pressure.",
    origin: "Mobile onboarding, social apps, delivery products, and productivity tools.",
  },
  {
    slug: "forced-registration",
    title: "Forced Registration",
    category: "Interface Manipulation",
    summary: "The content is visible right up until it becomes bait.",
    description:
      "Users are required to create an account before completing a task that could reasonably be done as a guest or anonymous visitor.",
    severity: 3,
    psychology: ["Commitment Bias", "Cognitive Load"],
    examples: ["Checkout requires an account after the basket is complete.", "A public article reveals a registration wall halfway down."],
    ethicalAlternative: "Offer guest flows and explain the benefits of accounts without making them mandatory by surprise.",
    origin: "Ecommerce, media sites, travel booking, and marketplaces.",
  },
  {
    slug: "autoplay-trap",
    title: "Autoplay Trap",
    category: "Attention Capture",
    summary: "The next video starts before intention can get its shoes on.",
    description:
      "Media automatically continues into another item, reducing natural stopping points and turning passive attention into longer sessions.",
    severity: 3,
    psychology: ["Commitment Bias", "FOMO"],
    examples: ["Next episode starts in five seconds.", "Short videos continue without a clear pause state."],
    ethicalAlternative: "Make autoplay opt-in, provide stopping cues, and remember user preferences.",
    origin: "Video platforms, streaming products, social feeds, and news sites.",
  },
  {
    slug: "streak-pressure",
    title: "Streak Pressure",
    category: "Gamification Abuse",
    summary: "A habit tracker becomes a small hostage situation.",
    description:
      "Streaks, badges, or progress counters are used to create anxiety around missing a day even when continued engagement is not meaningful.",
    severity: 3,
    psychology: ["Loss Aversion", "Commitment Bias"],
    examples: ["Do not lose your 186-day streak.", "Pay to repair a missed day."],
    ethicalAlternative: "Use streaks as optional reflection tools and avoid punishing breaks or selling relief from guilt.",
    origin: "Learning apps, fitness products, games, productivity tools, and wellness apps.",
  },
  {
    slug: "paywall-tease",
    title: "Paywall Tease",
    category: "Subscription Traps",
    summary: "The answer is always one paragraph below the subscription wall.",
    description:
      "A page offers enough visible content to create commitment, then blocks the key value behind a signup or paid plan.",
    severity: 3,
    psychology: ["Commitment Bias", "Loss Aversion"],
    examples: ["A recipe hides quantities after the introduction.", "A comparison article reveals the verdict only after registration."],
    ethicalAlternative: "State access limits upfront and mark premium content before the user invests time.",
    origin: "Media, recipe sites, education platforms, and research databases.",
  },
  {
    slug: "anchored-bundling",
    title: "Anchored Bundling",
    category: "Pricing Manipulation",
    summary: "The bundle looks like a bargain because the standalone prices were arranged to salute it.",
    description:
      "Individual items are priced or displayed so the bundle appears obviously superior, even when the user only needs part of it.",
    severity: 3,
    psychology: ["Anchoring", "Cognitive Load"],
    examples: ["Three tools cost 18€ each, or 29€ in a bundle the user may not need.", "The bundle is framed as saving 65% against inflated component prices."],
    ethicalAlternative: "Show realistic standalone value, let users compare actual needs, and avoid presenting unused features as savings.",
    origin: "SaaS suites, creator tools, ecommerce kits, and telecom packages.",
  },
  {
    slug: "review-gating",
    title: "Review Gating",
    category: "Trust & Authority Abuse",
    summary: "Happy users go public. Unhappy users go to a private form with excellent acoustics.",
    description:
      "A product routes satisfied customers to public review sites while directing dissatisfied customers to private support or feedback channels.",
    severity: 4,
    psychology: ["Social Proof", "Cognitive Load"],
    examples: ["Five-star survey respondents are asked to review publicly.", "Low-score respondents are sent to an internal feedback form."],
    ethicalAlternative: "Invite reviews consistently and make public reputation signals representative rather than filtered.",
    origin: "Local services, app stores, marketplaces, healthcare booking, and review widgets.",
  },
  {
    slug: "loyalty-lock-in",
    title: "Loyalty Lock-in",
    category: "Gamification Abuse",
    summary: "Points that feel like money until you try to leave.",
    description:
      "Rewards, points, tiers, or credits are designed to make users stay because leaving means abandoning accumulated value.",
    severity: 3,
    psychology: ["Loss Aversion", "Commitment Bias"],
    examples: ["You have 940 points, but rewards start at 1,000.", "Credits expire unless another purchase is made this month."],
    ethicalAlternative: "Make rewards simple to redeem, avoid punitive expiry, and let credits retain clear value.",
    origin: "Retail loyalty programs, airlines, delivery apps, games, and subscriptions.",
  },
  {
    slug: "scarcity-ladder",
    title: "Scarcity Ladder",
    category: "Urgency & Scarcity",
    summary: "First it is popular. Then limited. Then almost gone. A small opera in three badges.",
    description:
      "The interface escalates pressure through successive scarcity messages, making the user feel late even before they decide.",
    severity: 4,
    psychology: ["FOMO", "Loss Aversion", "Social Proof"],
    examples: ["Popular choice becomes limited stock, then only one left.", "A checkout shows demand, deadline, and inventory warnings together."],
    ethicalAlternative: "Use one accurate availability signal when it is relevant and avoid stacking pressure indicators.",
    origin: "Travel booking, ecommerce, ticketing, course launches, and flash sales.",
  },
  {
    slug: "ai-authority-washing",
    title: "AI Authority Washing",
    category: "Trust & Authority Abuse",
    summary: "The interface says AI recommended it, and hopes that sounds like evidence.",
    description:
      "A product invokes AI, algorithms, or personalization to make an option seem objective, expert, or uniquely suited without explaining the basis.",
    severity: 3,
    psychology: ["Social Proof", "Anchoring", "Cognitive Load"],
    examples: ["Recommended by AI appears beside the most expensive plan.", "A black-box score ranks an upsell as best for you."],
    ethicalAlternative: "Explain recommendation criteria, disclose commercial influence, and let users compare alternatives.",
    origin: "SaaS pricing, ecommerce recommendations, fintech, hiring tools, and health-adjacent apps.",
  },
  {
    slug: "negative-option-billing",
    title: "Negative Option Billing",
    category: "Subscription Traps",
    summary: "Silence is interpreted as a legally billable yes.",
    description:
      "The user is enrolled or renewed unless they actively opt out within a window that may be easy to miss.",
    severity: 5,
    psychology: ["Default Bias", "Commitment Bias", "Cognitive Load"],
    examples: ["Membership renews unless cancelled before a buried deadline.", "A trial extension becomes paid unless declined."],
    ethicalAlternative: "Require clear affirmative consent for billing and send timely reminders before renewal.",
    origin: "Membership clubs, subscription boxes, software renewals, and trial programs.",
  },
  {
    slug: "survey-to-sales-funnel",
    title: "Survey-to-Sales Funnel",
    category: "Social Engineering",
    summary: "It starts as a quiz and ends as a checkout with diagnostic confidence.",
    description:
      "A quiz, assessment, or survey gathers intent and then reframes the result as a personalized reason to buy.",
    severity: 3,
    psychology: ["Commitment Bias", "Anchoring"],
    examples: ["A skin quiz recommends the premium bundle.", "A productivity assessment ends with a limited plan offer."],
    ethicalAlternative: "Separate genuine assessment from sales pressure and explain how recommendations are generated.",
    origin: "Wellness, education, beauty, productivity, and coaching funnels.",
  },
  {
    slug: "visual-obstruction",
    title: "Visual Obstruction",
    category: "Interface Manipulation",
    summary: "The important control exists behind a sticky bar, modal, or conveniently placed enthusiasm.",
    description:
      "A banner, overlay, sticky element, or animation blocks access to content or controls, often making the commercial action easier than dismissal.",
    severity: 4,
    psychology: ["Cognitive Load", "Default Bias"],
    examples: ["A sticky app-install banner covers the reject button.", "A chat widget overlays the cancellation link."],
    ethicalAlternative: "Keep critical controls unobstructed and make overlays dismissible, accessible, and proportionate.",
    origin: "Mobile web, ecommerce, support widgets, app install prompts, and cookie banners.",
  },
  {
    slug: "like-gating",
    title: "Like-gating",
    category: "Social Engineering",
    summary: "Double-tap to reveal. Now tap again. And again.",
    description:
      "Content, features, or information are locked behind a required like, share, follow, or comment. Each engagement gate lowers the friction of the next, turning passive consumption into active promotion.",
    severity: 3,
    psychology: ["Commitment Bias", "Cognitive Load", "Social Proof"],
    examples: ["Tap heart to reveal the answer.", "Share with 3 friends to unlock the full guide.", "Follow to continue reading this thread."],
    ethicalAlternative: "Reveal content freely and let users engage because they find value, not because the interface locks value behind a transaction.",
    origin: "Social media, recipe sites, quiz platforms, and content marketing funnels.",
  },
  {
    slug: "validation-loop",
    title: "Validation Loop",
    category: "Gamification Abuse",
    summary: "A like arrives. Then another. Then one from three hours ago. Dopamine, dripped.",
    description:
      "Reaction notifications — likes, hearts, upvotes — are delivered on a variable-ratio schedule to create a compulsive checking habit. Each notification is a small social reward timed to pull the user back into the app.",
    severity: 3,
    psychology: ["Variable Reward", "FOMO", "Commitment Bias"],
    examples: ["Your photo received 14 new likes.", "X and 7 others liked your comment.", "Notifications arrive hours after the engagement to re-engage."],
    ethicalAlternative: "Batch notifications, let users choose delivery cadence, and avoid timing rewards to maximize checking behavior.",
    origin: "Social networks, dating apps, content platforms, and community products.",
  },
  {
    slug: "reaction-pressure",
    title: "Reaction Pressure",
    category: "Attention Capture",
    summary: "1 like = 1 prayer. 1 share = 1 tree. The math is emotional, not financial.",
    description:
      "Emotional messaging frames reactions as moral, charitable, or supportive acts, guilting the user into engaging. The reaction button becomes a social obligation.",
    severity: 3,
    psychology: ["Social Proof", "Reciprocity", "Loss Aversion"],
    examples: ["1 like = 1€ donated to clean water.", "Like if you think this is unacceptable.", "Share to show you care."],
    ethicalAlternative: "Let users react naturally without emotional framing. Support causes transparently without tying impact to engagement metrics.",
    origin: "Facebook, Instagram, TikTok, Twitter/X, and charitable campaigns.",
  },
  {
    slug: "hard-to-close",
    title: "Hard-to-Close",
    category: "Interface Manipulation",
    summary: "The close button exists. Technically. At 7 pixels. In low contrast.",
    description:
      "A modal, popup, or overlay makes the dismiss action deliberately hard to find or click — tiny target, low contrast, outside viewport, or hidden behind motion.",
    severity: 3,
    psychology: ["Cognitive Load", "Default Bias"],
    examples: ["A newsletter modal places the X in low-contrast grey outside the visible area on mobile.", "A cookie banner offers no close button, only a tiny text link among paragraphs."],
    ethicalAlternative: "Make close buttons at least 44×44px, high-contrast, and placed in a predictable location.",
    origin: "Newsletter popups, cookie banners, app-install interstitials, and ecommerce overlays.",
  },
];

export function getFeaturedPatterns() {
  return patterns.slice(0, 6);
}

export function getPattern(slug: string) {
  return patterns.find((pattern) => pattern.slug === slug);
}

export function getPatternsByCategory(category: string) {
  return patterns.filter((pattern) => pattern.category === category);
}
